// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAssetTracking.App.Data;

#nullable disable

namespace SmartAssetTracking.App.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    partial class AssetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SmartAssetTracking.App.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LocalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePriceUSD")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WarrantyExpiration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("AssetCategory").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.ComputerAsset", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.Asset");

                    b.Property<string>("CPU")
                        .HasColumnType("TEXT");

                    b.Property<string>("GPU")
                        .HasColumnType("TEXT");

                    b.Property<string>("RAM")
                        .HasColumnType("TEXT");

                    b.Property<string>("Storage")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.MobileAsset", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.Asset");

                    b.Property<string>("BatteryCapacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Mobile");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Desktop", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.ComputerAsset");

                    b.HasDiscriminator().HasValue("Desktop");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Laptop", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.ComputerAsset");

                    b.HasDiscriminator().HasValue("Laptop");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Nokia", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.MobileAsset");

                    b.HasDiscriminator().HasValue("Nokia");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Samsung", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.MobileAsset");

                    b.HasDiscriminator().HasValue("Samsung");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Tablet", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.MobileAsset");

                    b.HasDiscriminator().HasValue("Tablet");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.iPhone", b =>
                {
                    b.HasBaseType("SmartAssetTracking.App.Models.MobileAsset");

                    b.HasDiscriminator().HasValue("iPhone");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Asset", b =>
                {
                    b.HasOne("SmartAssetTracking.App.Models.Employee", "Employee")
                        .WithMany("Assets")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("SmartAssetTracking.App.Models.Office", "Office")
                        .WithMany("Assets")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("SmartAssetTracking.App.Models.Asset", "Asset")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Asset", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Employee", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("SmartAssetTracking.App.Models.Office", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
